apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  SERVICE_PORT: {{ .Values.env.SERVICE_PORT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL }}
  AWS_REGION: {{ .Values.env.AWS_REGION }}
  BEDROCK_MODEL_ID: {{ .Values.env.BEDROCK_MODEL_ID }}
  CLUSTER_NAME: {{ .Values.env.CLUSTER_NAME }}
