apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ustbite-aiops-service-prod-secret
  namespace: ustbite-ops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ustbite-aiops-service-prod-secret
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: /ustbite/prod/ops/admin-api-key
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: /ustbite/prod/ops/github-token
