apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ustbite-payment-service-prod-secret
  namespace: ustbite-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ustbite-payment-service-prod-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /ustbite/prod/payment-service/database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: /ustbite/prod/shared/redis-url
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: /ustbite/prod/shared/rabbitmq-url
    - secretKey: SECRET_KEY
      remoteRef:
        key: /ustbite/prod/shared/jwt-secret-key
    - secretKey: RAZORPAY_KEY_ID
      remoteRef:
        key: /ustbite/prod/payment-service/razorpay-key-id
    - secretKey: RAZORPAY_KEY_SECRET
      remoteRef:
        key: /ustbite/prod/payment-service/razorpay-key-secret
